services:
  cli:
    build: 
      args:
        cli_username: ${CLI_USERNAME}
        cli_uid: ${CLI_UID}
        cli_gid: ${CLI_GID}
        node_version: ${NODE_VERSION}
        php_version: ${PHP_VERSION}
      context: .
      dockerfile: Dockerfile-cli
    restart: unless-stopped
    command: sleep infinity
    volumes:
      - ..:/workspaces/${COMPOSE_PROJECT_NAME}:cached

  mailhog:
    image: mailhog/mailhog
    platform: linux/amd64
    ports:
      - ${MAILHOG_SMTP_PORT}:1025
      - ${MAILHOG_HTTP_PORT}:8025
    restart: unless-stopped

  mysql:
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    image: mysql:${MYSQL_VERSION}-debian
    platform: linux/amd64
    ports:
      - ${MYSQL_PORT}:3306
    restart: unless-stopped
    volumes:
      - ..:/app
      - mysql_data:/var/lib/mysql

  nginx:
    image: nginx:${NGINX_VERSION}
    ports:
      - ${NGINX_PORT}:80
    restart: unless-stopped
    volumes:
      - ..:/app
      - ./config/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

  php:
    build: 
      args:
        php_version: ${PHP_VERSION}
      context: .
      dockerfile: Dockerfile-php
    restart: unless-stopped
    volumes:
      - ..:/app

  redis:
    image: redis:${REDIS_VERSION}
    ports:
      - ${REDIS_PORT}:6379
    restart: unless-stopped
    volumes:
      - redis_data:/data

volumes:
  mysql_data: {}
  redis_data: {}
