ARG php_version

FROM php:${php_version}-fpm

RUN apt-get update \
    && apt-get install -y --no-install-recommends unzip libicu-dev pkg-config libzstd-dev \
    && docker-php-ext-install intl pdo_mysql \
    && pecl install redis && docker-php-ext-enable redis \
    && pecl install xdebug && docker-php-ext-enable xdebug

# install GD
RUN apt-get update && apt-get install -y libfreetype-dev libjpeg62-turbo-dev libpng-dev \
    && docker-php-ext-configure gd --with-freetype --with-jpeg \
    && docker-php-ext-install -j$(nproc) gd

RUN apt-get autoremove -y \
    && rm -rf /var/lib/apt/lists/* 
